### ISSUE TITLE
o-message/o-alert designs

### ISSUE THREAD

**Issue by draysonandstock** [Financial-Times/o-message#1]
_To create an alert component for any system messages needing to be shown to the user. These might be shown on page load (payment failure for example) or triggered by a user, such as on successfully submitting a form._ 

**_Sketch file of the designs can be found here: 
FT Design / components / o-messaging / sketch / o-messaging.sketch (then 'alert (systems)' page of the Sketch file)_**

n-alert-banner is the next component that can be used as a starting point. 
(https://github.com/Financial-Times/n-alert-banner)

**A bit more information (FT.com):**

There are two distinctly different designs, the first is a full width narrow bar that sticks just below the nav and stays with the sticky nav on scroll. As default this is dismissible but needs to have the option this being disabled. 

The second is an inline version of the alert which isn't dismissible and has a max width equal to o-forms of (380px) dropping down to 300px at mobile. 

Both designs have three flavours/themes to convey the type of message to the user. These are:

**Success** – uses the tick icon and a green colour palette (Jade)
**Good to know** – has a more neutral colour palette and is used for general messages or when a message doesn't clearly fall into the other two categories. 
**Error** – uses shades red (Crimson)

In addition to the above they all have the option of a semibold short message followed by a longer explanation and then either a small button, link or both.  At mobile breakpoints the longer explanation is dropped and a single next step/action is preserved.

**Comment by gvonkoss** [comment]
Closed by #7
