### ISSUE TITLE
Lack of detail in o-message documentation

### ISSUE THREAD

**Issue by HelenHTech** [Financial-Times/o-message#60]
- When using the JSDoc, and SassDoc pages for o-message, example would have made the process of implementing o-message more understandable
- The 'Options' section is not clear on how to add them into the code

**Comment by notlee** [comment]
Hey, it's certainly a tricky set of options to document! I've had a go at making improvements here but I'd appreciate any feedback you have :) https://github.com/Financial-Times/o-message/pull/62
