### ISSUE TITLE
Make inform variant stand out more in internal brand

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-message#69]
## What
I keep finding myself reaching for the 'warning light' variant because the 'inform' variant does not jump out at the user.

In particular because the shade of grey is widely used for other things in the internal brand, e.g.

![image](https://user-images.githubusercontent.com/447559/72916270-ab06c800-3d39-11ea-9ead-1e5a87d90ad0.png)

**Comment by wheresrhys** [comment]
Or maybe a new variant: `promotional` ?

**Comment by notlee** [comment]
🤔 I'll ask product design for some input. Here are all our internal messages:  https://registry.origami.ft.com/components/o-message@4.0.1/?brand=internal

**Comment by notlee** [comment]
There was some chat in Slack about this, from here onward:
https://financialtimes.slack.com/archives/C8U9J5YJ2/p1579778225003600

We might want a new accent palette colour for the internal brand for usecases like this.
https://financialtimes.slack.com/archives/C8U9J5YJ2/p1579780017007400
"a nice shade of pink perhaps" or "Velvet and Lemon [...], as they remind me of cake…."

**Comment by chee** [comment]
CANDY CANDY CANDY CANDY CANDY

**Comment by notlee** [comment]
I spoke to David and Jess about this, and later Emma. Here's my takaway:

David pointed out in some cases like the registry the inform message works well and is appropriately prominent. That maybe this is something new.
<img width="1306" alt="Screenshot 2020-01-30 at 11 45 42" src="https://user-images.githubusercontent.com/10405691/73546710-9612ee80-4435-11ea-9117-5d5b719ade4c.png">

Jess agrees that some messages could be more prominent. This is particularly the case for Spark where messages pop up and fade away without action -- o-message wasn't designed with this in mind. But in terms of the inform variant's colour that's a broader issue.

We discussed how calls for feedback are done elsewhere and noticed ft.com and FDI using a similar looking "feedback" tab to the right. Should this be an Origami pattern for feedback gathering we wonder?
<img width="1421" alt="Screenshot 2020-01-30 at 11 54 02" src="https://user-images.githubusercontent.com/10405691/73547296-86e07080-4436-11ea-889f-2148c085fb97.png">
<img width="1421" alt="Screenshot 2020-01-30 at 11 54 46" src="https://user-images.githubusercontent.com/10405691/73547297-86e07080-4436-11ea-871b-e5d7b3de65f6.png">

Jess suggests the new "feedback" button in the header of Spark could also use this pattern:
<img width="1421" alt="Screenshot 2020-01-31 at 14 29 40" src="https://user-images.githubusercontent.com/10405691/73547400-bdb68680-4436-11ea-94f5-3b8432c0ed32.png">

I'll open a proposal for a "feedback" component based on these comments.

I proposed this pattern to Rhys who pointed out Bizops already has a feedback button in the header for passive feedback, and that this message should be more prominent to advertise that survey input is actively being requested.
<img width="1421" alt="Screenshot 2020-01-30 at 11 54 18" src="https://user-images.githubusercontent.com/10405691/73547637-43d2cd00-4437-11ea-8aae-a25f83bc5330.png">
We chatted about the survey a little, and talked about how [o-banner](https://registry.origami.ft.com/components/o-banner) might be appropriate, but came to the conclusion there may be better ways to request people fill in the survey (including in person). Therefore I think this issue can be closed for now if you agree @wheresrhys?

**Comment by notlee** [comment]
@wheresrhys we've added custom slate support to o-message, with highlights. It would make a slate sandwhich but we could explore using this design from the master brand: https://github.com/Financial-Times/o-message/pull/75
